### ISSUE TITLE
Changes between version 2 and 3 of Irving and Holden

### ISSUE THREAD

**Issue by bgcarlisle** [dhimmel/irreproducible-timestamps#1]
I copied version 3 into LibreOffice and did the same with version 2. Then I used "Compare documents ..." which annotated all the differences between them. This has been attached as a Word document.

[v2-3.docx](https://github.com/dhimmel/irreproducible-timestamps/files/882799/v2-3.docx)

**Comment by bgcarlisle** [comment]
There are only a few changes.

# Amendments

The following text has been added:

> To clarify our approach to verifying the original transaction we have included text to confirm that this was done using the same Strongcoin© account used to generate the original transaction. We have also replaced the .docx copy of the file used to verify the transaction with the original .txt file.

The following text has been removed.

> The method we tested here was first proposed by Carlisle in the grey literature. Clear reference to the previously described method (Reference 6) has been added throughout the revised article.

# Methods

A sentence in the Methods was changed from this ...

> To do this a new account was created in Strongcoin©9 and the SHA256 digest used as the account password (private key)6.

... to this:

> To do this a new account was created in Strongcoin©9 and the SHA256 digest used as the account password to generate a private key6.

Another part of the Methods was changed from this ...

> An SHA256 digest was created as previously described and a corresponding private key, public key and bitcoin address generated6. The exact replication of the bitcoin address (1AHjCz2oEUTH8js4S8vViC8NKph4zCACXH) was then used to prove the documents existence in the blockchain using blockchain.info©10.

... to this:

> An SHA256 digest was created as previously described. The corresponding private key, public key and bitcoin address were confirmed using the original Strongcoin© account and blockchain.info©6. The bitcoin address (1AHjCz2oEUTH8js4S8vViC8NKph4zCACXH) was then used to prove the documents existence in the blockchain using blockchain.info©10.

A third sentence was changed from this ...

> This was used to create a further SHA256 digest and corresponding public, private key and bitcoin address3.

... to this: 

This was used to create a further SHA256 digest which differed to that for the pre-specified protocol and would not allow the and corresponding public, private key to be unlocked in Strongcoin©3.

# Results

Only one sentence was changed in the Results.

Version 2:

> Researchers were able to search for the transaction on the blockchain, confirm the date when the transaction occurred and verify the authenticity of the original protocol by generating identical public and private keys. Any changes made to the original document generated different public and private keys indicating that protocol had been altered.

Version 3:

> Researchers were able to search for the transaction on the blockchain, confirm the date when the transaction occurred and verify the authenticity of the original protocol. Any changes made to the original document generated a different SHA 256 digest indicating that protocol had been altered.

# Supplementary materials

The original .DOCX file was replaced with a .TXT file.

These are the only changes that have been made between versions 2 and 3.

**Comment by dhimmel** [comment]
@bgcarlisle awesome. Can you export that diffed word doc to a PDF that shows the changes? Then submit a pull request to add the PDF to `f1000`?

Then we can timestamp the git commit hash :smile_cat: (which is as good as SHA1 -- not very).

**Comment by dhimmel** [comment]
Added an [update to my blog post](http://blog.dhimmel.com/irreproducible-timestamps/#update-on-march-30-2017) based on these changes.
