### ISSUE TITLE
Diff between version 1 & 2 of Irving & Holden

### ISSUE THREAD

**Issue by dhimmel** [dhimmel/irreproducible-timestamps#3]
@bgcarlisle, any chance you made a diff for v1-2 like [v2-3.pdf](https://github.com/dhimmel/irreproducible-timestamps/blob/60dae64e27611f7420424d0a5f71061e44d27d40/f1000/v2-3.pdf)? These diffs are super useful for untangling the evolution of Irving & Holden's incompetence / misconduct.

**Comment by bgcarlisle** [comment]
Yeah, pull request sent!
